### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by KorobetskayaAA** [MuromtsevSA/sorting-3-3#1]
Ваше решение, в принципе, работает, но в нем есть пара косяков.

1. Вы задали списку id, но нигде его не используете, т.к. ищете все li на странице. При этом, если у вас будет несколько списков, их пункты перемешаются. Правильно - найти сначала сам список по id, а уже внутри этого сиска выбрать li.
1. Вы выполняете сортировку массива sorted после добавления каждого элемента, внутри цикла. А надо делать один раз, после того, как все элементы уже добавили.

**Comment by MuromtsevSA** [comment]
Переделал

**Comment by MuromtsevSA** [comment]
> Есть пара косяков.
> 
> 1. Вы задаете список идентификаторов, но нигде его не используете, т.к. ищут все li на странице. При этом, если у вас будет несколько списков, их пункты будут добавлены. Правильно - найти сначала сам список по id, а уже внутри этого сиска выбрать li.
> 2. Вы выполняете сортировку массива отсортировано после добавления каждого элемента, внутри цикла. Все элементы уже добавлены.

Переделал сортировку
